In [23]:
%run "../config.py"

declared 4 variables


In [24]:
import os
import torch

In [25]:
# os.environ["HSA_OVERRIDE_GFX_VERSION"] = "10.3.0"

In [26]:
A = torch.randn((8,3,5))
A.size()

torch.Size([8, 3, 5])

In [27]:
A[:,:2,:3]

tensor([[[ 0.3858, -1.5649, -0.1687],
         [-0.6291,  0.2683,  0.5117]],

        [[-0.0723,  1.7865,  0.2467],
         [ 0.0465, -0.3685, -1.4667]],

        [[ 0.2833,  0.5126, -0.2927],
         [-0.1553,  0.7923, -0.0162]],

        [[ 0.2944,  2.7270, -0.2981],
         [-2.4085, -1.6688, -0.9424]],

        [[ 0.4572,  0.9232,  0.3145],
         [-0.7489, -0.4943,  1.2727]],

        [[-0.3932,  1.6780, -1.7897],
         [ 0.0338, -0.6062, -0.6691]],

        [[-1.0173, -0.1916,  0.2507],
         [-0.7967,  0.3305,  0.5060]],

        [[-0.1159,  0.5025,  0.9831],
         [-1.4508,  0.8019,  0.2529]]])

In [28]:
C = torch.zeros((5,5))
C.dtype

torch.float32

In [29]:
D = torch.randint(2, (5,5))
D

tensor([[1, 1, 1, 1, 0],
        [1, 0, 1, 0, 1],
        [1, 0, 0, 1, 0],
        [1, 1, 1, 1, 0],
        [0, 1, 1, 0, 0]])

In [30]:
C + D

tensor([[1., 1., 1., 1., 0.],
        [1., 0., 1., 0., 1.],
        [1., 0., 0., 1., 0.],
        [1., 1., 1., 1., 0.],
        [0., 1., 1., 0., 0.]])

In [31]:
torch.device('privateuseone:1')

device(type='privateuseone', index=1)

In [32]:
torch.__version__

'1.13.1+cpu'

In [33]:
torch.ops.load_library("/home/rml/Desktop/pytorch_dlprim/build/libpt_ocl.so")

In [34]:
DEVICE = torch.device("privateuseone:1")

In [36]:
tensor = torch.tensor((5.,1.,2.), dtype=torch.float32)
tensor

RuntimeError: Invalid Device #1